#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/academy
#    password: '1234'
#  output:
#    ansi:
#      enabled: always
#  jpa:
#    hibernate:
#      ddl-auto: update

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always