spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

jwt:
  secret: 7z!A&D*G-KaPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F-JaNcRfUjXn
  expiration: 86400000