spring:
  datasource:
    url: jdbc:postgresql://ep-dark-bird-acrgeog7-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_6ymIQArSjb3G
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

jwt:
  secret: 7z!A&D*G-KaPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F-JaNcRfUjXn
  expiration: 86400000